#!/usr/bin/env bash
# populate.sh — capture the live machine's ai-harness picker artifacts back
# INTO this repo. Exact inverse of install.sh (which deploys repo ->
# ~/.ai-harness).
#
# This box (~/.ai-harness, ~/.zsh-aliases) is the source of truth for the
# picker layer: the ai/air wrapper and the provider catalog. Run this, review
# `git diff`, then commit and push.
#
# Policy (explicit allowlists; nothing is auto-discovered):
#   ai.py, providers.yaml   from ~/.ai-harness/
#   sh-aliases/ai           from ~/.zsh-aliases/ai (picker flavor only)
# hooks/, plugins/, agents/, skills/ are NOT captured yet — their deploy comes
# at cutover and the repo stays their source of truth. adapters/ likewise.
# Excluded explicitly: .venv/ (recreate via install.sh), backups/,
# $CODEX_HOME/ai-*.config.toml (generated), and ~/.secrets/.
#
# Because this repo is PUBLIC, the capture is followed by the leak gate
# (scripts/leak-scan.sh): secret values + employer/internal identifiers from a
# gitignored patterns file. The script covers the whole tracked tree, so the
# freshly captured files are in scope.
#
# Usage:
#   ./populate.sh            # capture, leak-check, show git status
#   ./populate.sh --dry-run  # print planned actions, copy nothing

set -euo pipefail

# --- destination (this repo) ---
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- live sources (this machine) ---
LIVE_HARNESS="$HOME/.ai-harness"
LIVE_ALIASES="$HOME/.zsh-aliases"

DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

say()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
skip() { printf '    \033[1;33mskip\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

run() { if $DRY_RUN; then printf '    [dry-run] %s\n' "$*"; else eval "$@"; fi; }

# Copy a file into the repo, creating parent dirs. An existing destination
# keeps its current mode (cp does not reset the mode of a file that exists),
# so the repo's executable bits survive a capture.
cp_file() {
  local src="$1" dst="$2"
  [[ -f "$src" ]] || { skip "missing source: $src"; return 0; }
  if cmp -s "$src" "$dst" 2>/dev/null; then
    printf '    --   %s (unchanged)\n' "${dst#$REPO/}"
    return 0
  fi
  run "mkdir -p '$(dirname "$dst")'"
  run "cp '$src' '$dst'"
  printf '    ok   %s\n' "${dst#$REPO/}"
}

[[ -d "$REPO/.git" ]] || die "not a git repo: $REPO"
[[ -d "$LIVE_HARNESS" ]] || die "no live ~/.ai-harness at $LIVE_HARNESS (run install.sh first)"

say "capturing picker artifacts: $LIVE_HARNESS -> $REPO"

# ── picker: ai/air wrapper + provider catalog ──────────────────────────────
say "picker  (ai.py, providers.yaml)"
cp_file "$LIVE_HARNESS/ai.py"          "$REPO/ai.py"
cp_file "$LIVE_HARNESS/providers.yaml" "$REPO/providers.yaml"

# ── shell alias ────────────────────────────────────────────────────────────
say "sh-aliases/  (ai -> ai / air / ccprov)"
# ~/.zsh-aliases/ai is machine-specific in general: another host may keep a
# different launcher there. The repo only owns the picker flavor, identified
# by its header line — never capture anything else over it.
if grep -q 'fzf-driven multi-CLI' "$LIVE_ALIASES/ai" 2>/dev/null; then
  cp_file "$LIVE_ALIASES/ai" "$REPO/sh-aliases/ai"
else
  skip "$LIVE_ALIASES/ai is not the picker flavor (machine-specific) — not captured"
fi

# ── not captured, for the record ───────────────────────────────────────────
say "later phases  (install/deploy comes at cutover)"
for d in hooks agents adapters; do skip "$d/ (edit in-repo)"; done
skip ".venv/ (recreate via install.sh)"
skip "backups/ (local only)"
skip "~/.codex/ai-*.config.toml (generated by ai.py)"
skip "~/.secrets/ (tokens — never in a repo)"

# ── skills drift gate ──────────────────────────────────────────────────────
# skills/ is canonical; plugins/<p>/skills/<name>/ must mirror it exactly.
# No CI here, so this check rides the capture path: populate.sh fails loudly
# if a plugin copy has drifted (fix: scripts/sync-skills.sh --fix).
if ! $DRY_RUN; then
  say "skills drift check (scripts/sync-skills.sh)"
  "$REPO/scripts/sync-skills.sh"
fi

# ── safety net: this repo is PUBLIC ────────────────────────────────────────
# scripts/leak-scan.sh: secret values always, internal identifiers from the
# gitignored patterns file. It scans tracked files only (`git ls-files`), so
# the freshly captured paths get an intent-to-add record first (`git add -N`)
# — that puts them in scope without staging any content. The pre-push hook
# re-runs the same scan as the last line of defense.
if ! $DRY_RUN; then
  say "leak check (scripts/leak-scan.sh)"
  git -C "$REPO" add -N ai.py providers.yaml sh-aliases/ai 2>/dev/null || true
  "$REPO/scripts/leak-scan.sh"
fi

# ── summary ────────────────────────────────────────────────────────────────
if $DRY_RUN; then
  say "dry-run complete — nothing written"
else
  say "done. Review and commit:"
  ( cd "$REPO" && git status --short 2>/dev/null | sed 's/^/    /' )
  printf '    (from %s: git add -A && git commit && git push)\n' "$REPO"
fi
